allowBuilds:
  '@heroui/shared-utils': true
  '@tailwindcss/oxide': true
  bufferutil: true
  core-js: true
  esbuild: true
  protobufjs: true
  sharp: true
  tiny-secp256k1: true
  unrs-resolver: true
  utf-8-validate: true

overrides:
  '@tanstack/react-query': ^5.101.0

